version: '3.4'

services:
  flask:
    image: flask
    container_name: flask
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 4444"]
    ports:
      - 4444:4444
      - 5678:5678
    environment:
      - FLASK_APP=staj.py
