version: '3'

services: 
    flask:
      build:
        context: ./flask
      ports:
          - 4444:4444
      container_name: flask
      
    nodejs:
      build:
        context: ./nodejs
      ports:
           - 5555:5555
      container_name: nodejs

    haproxy:
     build: ./haproxy
     container_name: haproxy
     ports:
        - 8888:8888